package guiFactory.principal;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import guiFactory.perfis.FabricaDePerfis;
import guiFactory.perfis.FabricaDoPerfilDoCruzeiro;
import guiFactory.perfis.FabricaDoPerfilDoAtletico;

public class TelaComPadraoDeProjeto extends javax.swing.JFrame {
    private FabricaDePerfis fp;
    
    /**
     * Creates new form TelaComPadraoDeProjeto
     */
    public TelaComPadraoDeProjeto() {
        initComponents();
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja utilizar o perfil do Cruzeiro?");
        if (opcao == JOptionPane.YES_OPTION) {
            fp = new FabricaDoPerfilDoCruzeiro();
        }
        else {
            JOptionPane.showMessageDialog(this, "Não acredito que prefere o Atlético... tsc tsc tsc");
            fp = new FabricaDoPerfilDoAtletico();
        }
        construirTela(fp);
    }
    
    private void construirTela(FabricaDePerfis fp) {
        JPanel painel = fp.criarPainel();
        JLabel rotulo = fp.criarRotulo();
        rotulo.setText("Digite aqui seu nome: ");
        JTextField caixaDeTexto = fp.criarCaixaDeTexto();
        caixaDeTexto.setColumns(5);
        JButton botao = fp.criarBotao();
        botao.setText("Enviar");        
        
        this.setTitle("Tela Inicial");
        this.setContentPane(painel);
        this.add(rotulo);
        this.add(caixaDeTexto);
        this.add(botao);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaComPadraoDeProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaComPadraoDeProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaComPadraoDeProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaComPadraoDeProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaComPadraoDeProjeto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
