package guiFactory.principal;

import guiFactory.elementosGraficosTimao.BotaoDoCruzeiro;
import guiFactory.elementosGraficosTimao.CaixaTextoDoCruzeiro;
import guiFactory.elementosGraficosTimao.PainelDoCruzeiro;
import guiFactory.elementosGraficosTimao.RotuloDoCruzeiro;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Paulo
 */
public class TelaSemPadraoDeProjeto extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaComPadraoDeProjeto
     */
    public TelaSemPadraoDeProjeto() {
        initComponents();
        construirTela();
        JOptionPane.showMessageDialog(this, "Repare no código como seria trabalhoso trocar o perfil da tela.");
    }
    
    private void construirTela() {
        JPanel painel = new PainelDoCruzeiro();
        JLabel rotulo = new RotuloDoCruzeiro();
        rotulo.setText("Digite aqui seu nome: ");
        JTextField caixaDeTexto = new CaixaTextoDoCruzeiro();
        caixaDeTexto.setColumns(5);
        JButton botao = new BotaoDoCruzeiro();
        botao.setText("Enviar");        
        
        this.setTitle("Tela Inicial");
        this.setContentPane(painel);
        this.add(rotulo);
        this.add(caixaDeTexto);
        this.add(botao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSemPadraoDeProjeto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
